datasets:
  mvtec_ad:
    data_type: images
    build_info:
      image_path: /mnt/Repository/MiniGPT-4/MVTEC_det/images
      ann_path: /mnt/Repository/MiniGPT-4/MVTEC_det/mvtech_ad_data_for_regression.json
